export const ERROR_CODES = {
  VALIDATION: "VALIDATION",
  PERSISTENCE: "PERSISTENCE",
  NETWORK: "NETWORK",
  TIMEOUT: "TIMEOUT",
  AUTHENTICATION: "AUTHENTICATION",
  AUTHORIZATION: "AUTHORIZATION",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  RATE_LIMIT: "RATE_LIMIT",
  MEDIA_PERMISSION: "MEDIA_PERMISSION",
  MEDIA_UNAVAILABLE: "MEDIA_UNAVAILABLE",
  PHYSICS_DOMAIN: "PHYSICS_DOMAIN",
  SIMULATION: "SIMULATION",
  TUTOR_SERVICE: "TUTOR_SERVICE",
  SERIALIZATION: "SERIALIZATION",
  MIGRATION: "MIGRATION",
  CONFIGURATION: "CONFIGURATION",
  UNKNOWN: "UNKNOWN",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export const ERROR_CATEGORIES = {
  ValidationError: ERROR_CODES.VALIDATION,
  PersistenceError: ERROR_CODES.PERSISTENCE,
  NetworkError: ERROR_CODES.NETWORK,
  TimeoutError: ERROR_CODES.TIMEOUT,
  AuthenticationError: ERROR_CODES.AUTHENTICATION,
  AuthorizationError: ERROR_CODES.AUTHORIZATION,
  NotFoundError: ERROR_CODES.NOT_FOUND,
  ConflictError: ERROR_CODES.CONFLICT,
  RateLimitError: ERROR_CODES.RATE_LIMIT,
  MediaPermissionError: ERROR_CODES.MEDIA_PERMISSION,
  MediaUnavailableError: ERROR_CODES.MEDIA_UNAVAILABLE,
  PhysicsDomainError: ERROR_CODES.PHYSICS_DOMAIN,
  SimulationError: ERROR_CODES.SIMULATION,
  TutorServiceError: ERROR_CODES.TUTOR_SERVICE,
  SerializationError: ERROR_CODES.SERIALIZATION,
  MigrationError: ERROR_CODES.MIGRATION,
  ConfigurationError: ERROR_CODES.CONFIGURATION,
  UnknownAppError: ERROR_CODES.UNKNOWN,
} as const;

export type ErrorCategory = keyof typeof ERROR_CATEGORIES;

export const RETRYABLE_ERROR_CODES: ReadonlySet<ErrorCode> = new Set([
  ERROR_CODES.NETWORK,
  ERROR_CODES.TIMEOUT,
  ERROR_CODES.RATE_LIMIT,
  ERROR_CODES.TUTOR_SERVICE,
]);

export const PERMANENT_ERROR_CODES: ReadonlySet<ErrorCode> = new Set([
  ERROR_CODES.VALIDATION,
  ERROR_CODES.AUTHENTICATION,
  ERROR_CODES.AUTHORIZATION,
  ERROR_CODES.NOT_FOUND,
  ERROR_CODES.PHYSICS_DOMAIN,
  ERROR_CODES.SERIALIZATION,
  ERROR_CODES.CONFIGURATION,
]);
