import type { BillingState, Subscription, Tier } from "./compat";
import type { BillingPeriod, MonetizationUserState, TrialLifecycle } from "./types";

export type MockBillingScenarioId =
  | "FREE_USER"
  | "TRIAL_USER"
  | "PLUS_MONTHLY"
  | "PLUS_ANNUAL"
  | "LIFETIME_USER"
  | "EXPIRED_USER"
  | "CANCELLED_USER"
  | "BILLING_RETRY"
  | "GRACE_PERIOD"
  | "PENDING_PURCHASE"
  | "PURCHASE_ERROR"
  | "RESTORE_SUCCESS"
  | "RESTORE_FAILURE"
  | "OFFLINE_USER"
  | "NO_PRODUCTS"
  | "PRODUCTS_LOADING"
  | "PRODUCT_CONFIG_ERROR"
  | "ALREADY_PREMIUM"
  | "ALREADY_LIFETIME"
  | "UPGRADE_MONTHLY_ANNUAL"
  | "UPGRADE_MONTHLY_LIFETIME"
  | "TRIAL_TO_ANNUAL"
  | "TRIAL_EXPIRED"
  | "SUBSCRIPTION_PAUSED"
  | "SUBSCRIPTION_REVOKED"
  | "PRICE_CHANGE"
  | "STORE_UNAVAILABLE"
  | "REGION_UNSUPPORTED"
  | "UNKNOWN_ENTITLEMENT"
  | "PARTIAL_ENTITLEMENT"
  | "SERVER_SYNC_DELAY"
  | "PAYMENT_ERROR"
  | "RESTORE_USER";

export type MockPurchaseOutcome = "success" | "pending" | "cancelled" | "failed" | "offline" | "unavailable" | "already_owned";
export type MockRestoreOutcome = "restored" | "nothing_found" | "partial" | "failed" | "offline";

export type MockBillingScenario = {
  id: MockBillingScenarioId;
  label: string;
  description: string;
  userState: MonetizationUserState;
  providerAvailable: boolean;
  connected: boolean;
  productsAvailable: boolean;
  productsLoading?: boolean;
  configurationError?: boolean;
  subscription?: Subscription;
  lifetimeOwned: boolean;
  trialState: TrialLifecycle;
  purchaseOutcome: MockPurchaseOutcome;
  restoreOutcome: MockRestoreOutcome;
  billingPeriod?: BillingPeriod;
  paused?: boolean;
  revoked?: boolean;
  priceChange?: boolean;
  syncDelayMs: number;
  partialFeatures?: boolean;
};

function sub(tier: Tier, state: BillingState, productId: string | undefined, expiresAt?: string): Subscription {
  return { tier, state, productId, expiresAt };
}

const PLUS_MONTHLY = "dev.bav.plus.monthly";
const PLUS_ANNUAL = "dev.bav.plus.annual";
const LIFETIME = "dev.bav.lifetime";
const FUTURE = "2027-09-14T16:00:00.000Z";
const PAST = "2026-01-01T00:00:00.000Z";
const SOON = "2026-09-15T16:00:00.000Z";

export const MOCK_BILLING_SCENARIOS: Record<MockBillingScenarioId, MockBillingScenario> = {
  FREE_USER: {
    id: "FREE_USER",
    label: "Free user",
    description: "No paid entitlement. Core learning remains fully available.",
    userState: "free",
    providerAvailable: true,
    connected: true,
    productsAvailable: true,
    lifetimeOwned: false,
    trialState: "notStarted",
    purchaseOutcome: "success",
    restoreOutcome: "nothing_found",
    subscription: sub("free", "active", undefined),
    syncDelayMs: 0,
  },
  TRIAL_USER: {
    id: "TRIAL_USER",
    label: "Trial user",
    description: "Active trial of BAV+.",
    userState: "trial",
    providerAvailable: true,
    connected: true,
    productsAvailable: true,
    lifetimeOwned: false,
    trialState: "active",
    purchaseOutcome: "success",
    restoreOutcome: "restored",
    subscription: sub("plus", "trial", PLUS_ANNUAL, FUTURE),
    billingPeriod: "annual",
    syncDelayMs: 0,
  },
  PLUS_MONTHLY: {
    id: "PLUS_MONTHLY",
    label: "Monthly subscriber",
    description: "Active BAV+ monthly subscription.",
    userState: "plus_monthly",
    providerAvailable: true,
    connected: true,
    productsAvailable: true,
    lifetimeOwned: false,
    trialState: "converted",
    purchaseOutcome: "already_owned",
    restoreOutcome: "restored",
    subscription: sub("plus", "active", PLUS_MONTHLY, FUTURE),
    billingPeriod: "monthly",
    syncDelayMs: 0,
  },
  PLUS_ANNUAL: {
    id: "PLUS_ANNUAL",
    label: "Annual subscriber",
    description: "Active BAV+ annual subscription.",
    userState: "plus_annual",
    providerAvailable: true,
    connected: true,
    productsAvailable: true,
    lifetimeOwned: false,
    trialState: "converted",
    purchaseOutcome: "already_owned",
    restoreOutcome: "restored",
    subscription: sub("plus", "active", PLUS_ANNUAL, FUTURE),
    billingPeriod: "annual",
    syncDelayMs: 0,
  },
  LIFETIME_USER: {
    id: "LIFETIME_USER",
    label: "Lifetime user",
    description: "Non-consumable lifetime unlock. Not a subscription.",
    userState: "lifetime",
    providerAvailable: true,
    connected: true,
    productsAvailable: true,
    lifetimeOwned: true,
    trialState: "ineligible",
    purchaseOutcome: "already_owned",
    restoreOutcome: "restored",
    subscription: sub("lifetime", "active", LIFETIME),
    billingPeriod: "lifetime",
    syncDelayMs: 0,
  },
  EXPIRED_USER: {
    id: "EXPIRED_USER",
    label: "Expired subscriber",
    description: "Paid access ended. Free learning remains.",
    userState: "expired",
    providerAvailable: true,
    connected: true,
    productsAvailable: true,
    lifetimeOwned: false,
    trialState: "expired",
    purchaseOutcome: "success",
    restoreOutcome: "nothing_found",
    subscription: sub("plus", "expired", PLUS_MONTHLY, PAST),
    billingPeriod: "monthly",
    syncDelayMs: 0,
  },
  CANCELLED_USER: {
    id: "CANCELLED_USER",
    label: "Cancelled subscriber",
    description: "Cancellation recorded. Access follows remaining paid time if still active, otherwise free.",
    userState: "cancelled",
    providerAvailable: true,
    connected: true,
    productsAvailable: true,
    lifetimeOwned: false,
    trialState: "converted",
    purchaseOutcome: "success",
    restoreOutcome: "nothing_found",
    subscription: sub("plus", "canceled", PLUS_MONTHLY, PAST),
    billingPeriod: "monthly",
    syncDelayMs: 0,
  },
  BILLING_RETRY: {
    id: "BILLING_RETRY",
    label: "Billing retry",
    description: "Store is retrying a renewal. Access is not treated as permanently lost.",
    userState: "billing_retry",
    providerAvailable: true,
    connected: true,
    productsAvailable: true,
    lifetimeOwned: false,
    trialState: "converted",
    purchaseOutcome: "pending",
    restoreOutcome: "restored",
    subscription: sub("plus", "grace", PLUS_MONTHLY, SOON),
    billingPeriod: "monthly",
    syncDelayMs: 0,
  },
  GRACE_PERIOD: {
    id: "GRACE_PERIOD",
    label: "Grace period",
    description: "Temporary access while billing is being retried.",
    userState: "grace",
    providerAvailable: true,
    connected: true,
    productsAvailable: true,
    lifetimeOwned: false,
    trialState: "converted",
    purchaseOutcome: "success",
    restoreOutcome: "restored",
    subscription: sub("plus", "grace", PLUS_ANNUAL, SOON),
    billingPeriod: "annual",
    syncDelayMs: 0,
  },
  PENDING_PURCHASE: {
    id: "PENDING_PURCHASE",
    label: "Pending purchase",
    description: "Ask-to-buy or deferred payment. Entitlement is not granted yet.",
    userState: "pending",
    providerAvailable: true,
    connected: true,
    productsAvailable: true,
    lifetimeOwned: false,
    trialState: "notStarted",
    purchaseOutcome: "pending",
    restoreOutcome: "nothing_found",
    subscription: sub("plus", "pending", PLUS_MONTHLY),
    billingPeriod: "monthly",
    syncDelayMs: 0,
  },
  PURCHASE_ERROR: {
    id: "PURCHASE_ERROR",
    label: "Purchase error",
    description: "The next purchase attempt fails at the store.",
    userState: "free",
    providerAvailable: true,
    connected: true,
    productsAvailable: true,
    lifetimeOwned: false,
    trialState: "notStarted",
    purchaseOutcome: "failed",
    restoreOutcome: "nothing_found",
    subscription: sub("free", "active", undefined),
    syncDelayMs: 0,
  },
  RESTORE_SUCCESS: {
    id: "RESTORE_SUCCESS",
    label: "Restore success",
    description: "Restore finds an annual subscription.",
    userState: "plus_annual",
    providerAvailable: true,
    connected: true,
    productsAvailable: true,
    lifetimeOwned: false,
    trialState: "converted",
    purchaseOutcome: "already_owned",
    restoreOutcome: "restored",
    subscription: sub("plus", "active", PLUS_ANNUAL, FUTURE),
    billingPeriod: "annual",
    syncDelayMs: 0,
  },
  RESTORE_FAILURE: {
    id: "RESTORE_FAILURE",
    label: "Restore failure",
    description: "Restore cannot reach the store.",
    userState: "free",
    providerAvailable: true,
    connected: true,
    productsAvailable: true,
    lifetimeOwned: false,
    trialState: "notStarted",
    purchaseOutcome: "success",
    restoreOutcome: "failed",
    subscription: sub("free", "active", undefined),
    syncDelayMs: 0,
  },
  OFFLINE_USER: {
    id: "OFFLINE_USER",
    label: "Offline",
    description: "Purchasing requires connectivity. Cached access is time-bounded.",
    userState: "offline",
    providerAvailable: true,
    connected: false,
    productsAvailable: false,
    lifetimeOwned: false,
    trialState: "notStarted",
    purchaseOutcome: "offline",
    restoreOutcome: "offline",
    subscription: sub("free", "active", undefined),
    syncDelayMs: 0,
  },
  NO_PRODUCTS: {
    id: "NO_PRODUCTS",
    label: "No products",
    description: "The catalog cannot be loaded. Do not invent prices.",
    userState: "free",
    providerAvailable: true,
    connected: true,
    productsAvailable: false,
    lifetimeOwned: false,
    trialState: "notStarted",
    purchaseOutcome: "unavailable",
    restoreOutcome: "nothing_found",
    subscription: sub("free", "active", undefined),
    syncDelayMs: 0,
  },
  PRODUCTS_LOADING: {
    id: "PRODUCTS_LOADING",
    label: "Products loading",
    description: "Catalog is still loading.",
    userState: "free",
    providerAvailable: true,
    connected: true,
    productsAvailable: true,
    productsLoading: true,
    lifetimeOwned: false,
    trialState: "notStarted",
    purchaseOutcome: "success",
    restoreOutcome: "nothing_found",
    subscription: sub("free", "active", undefined),
    syncDelayMs: 800,
  },
  PRODUCT_CONFIG_ERROR: {
    id: "PRODUCT_CONFIG_ERROR",
    label: "Product configuration error",
    description: "Store IDs are invalid.",
    userState: "free",
    providerAvailable: false,
    connected: true,
    productsAvailable: false,
    configurationError: true,
    lifetimeOwned: false,
    trialState: "notStarted",
    purchaseOutcome: "unavailable",
    restoreOutcome: "failed",
    syncDelayMs: 0,
  },
  ALREADY_PREMIUM: {
    id: "ALREADY_PREMIUM",
    label: "Already premium",
    description: "User already has BAV+.",
    userState: "plus_annual",
    providerAvailable: true,
    connected: true,
    productsAvailable: true,
    lifetimeOwned: false,
    trialState: "converted",
    purchaseOutcome: "already_owned",
    restoreOutcome: "restored",
    subscription: sub("plus", "active", PLUS_ANNUAL, FUTURE),
    billingPeriod: "annual",
    syncDelayMs: 0,
  },
  ALREADY_LIFETIME: {
    id: "ALREADY_LIFETIME",
    label: "Already lifetime",
    description: "Lifetime already owned. Further subscriptions are unnecessary.",
    userState: "lifetime",
    providerAvailable: true,
    connected: true,
    productsAvailable: true,
    lifetimeOwned: true,
    trialState: "ineligible",
    purchaseOutcome: "already_owned",
    restoreOutcome: "restored",
    subscription: sub("lifetime", "active", LIFETIME),
    billingPeriod: "lifetime",
    syncDelayMs: 0,
  },
  UPGRADE_MONTHLY_ANNUAL: {
    id: "UPGRADE_MONTHLY_ANNUAL",
    label: "Upgrade monthly → annual",
    description: "Monthly subscriber considering annual.",
    userState: "plus_monthly",
    providerAvailable: true,
    connected: true,
    productsAvailable: true,
    lifetimeOwned: false,
    trialState: "converted",
    purchaseOutcome: "success",
    restoreOutcome: "restored",
    subscription: sub("plus", "active", PLUS_MONTHLY, FUTURE),
    billingPeriod: "monthly",
    syncDelayMs: 0,
  },
  UPGRADE_MONTHLY_LIFETIME: {
    id: "UPGRADE_MONTHLY_LIFETIME",
    label: "Upgrade monthly → lifetime",
    description: "Monthly subscriber considering lifetime unlock.",
    userState: "plus_monthly",
    providerAvailable: true,
    connected: true,
    productsAvailable: true,
    lifetimeOwned: false,
    trialState: "converted",
    purchaseOutcome: "success",
    restoreOutcome: "restored",
    subscription: sub("plus", "active", PLUS_MONTHLY, FUTURE),
    billingPeriod: "monthly",
    syncDelayMs: 0,
  },
  TRIAL_TO_ANNUAL: {
    id: "TRIAL_TO_ANNUAL",
    label: "Trial → annual",
    description: "Trial user converting to annual.",
    userState: "trial",
    providerAvailable: true,
    connected: true,
    productsAvailable: true,
    lifetimeOwned: false,
    trialState: "endingSoon",
    purchaseOutcome: "success",
    restoreOutcome: "restored",
    subscription: sub("plus", "trial", PLUS_ANNUAL, SOON),
    billingPeriod: "annual",
    syncDelayMs: 0,
  },
  TRIAL_EXPIRED: {
    id: "TRIAL_EXPIRED",
    label: "Trial expired",
    description: "Trial ended without conversion.",
    userState: "expired",
    providerAvailable: true,
    connected: true,
    productsAvailable: true,
    lifetimeOwned: false,
    trialState: "expired",
    purchaseOutcome: "success",
    restoreOutcome: "nothing_found",
    subscription: sub("plus", "expired", PLUS_ANNUAL, PAST),
    billingPeriod: "annual",
    syncDelayMs: 0,
  },
  SUBSCRIPTION_PAUSED: {
    id: "SUBSCRIPTION_PAUSED",
    label: "Subscription paused",
    description: "Store pause. Premium is not assumed.",
    userState: "expired",
    providerAvailable: true,
    connected: true,
    productsAvailable: true,
    lifetimeOwned: false,
    trialState: "converted",
    purchaseOutcome: "success",
    restoreOutcome: "partial",
    subscription: sub("plus", "expired", PLUS_MONTHLY, PAST),
    paused: true,
    billingPeriod: "monthly",
    syncDelayMs: 0,
  },
  SUBSCRIPTION_REVOKED: {
    id: "SUBSCRIPTION_REVOKED",
    label: "Subscription revoked",
    description: "Access revoked by the store. Local progress is kept.",
    userState: "expired",
    providerAvailable: true,
    connected: true,
    productsAvailable: true,
    lifetimeOwned: false,
    trialState: "converted",
    purchaseOutcome: "failed",
    restoreOutcome: "nothing_found",
    subscription: sub("plus", "canceled", PLUS_MONTHLY, PAST),
    revoked: true,
    billingPeriod: "monthly",
    syncDelayMs: 0,
  },
  PRICE_CHANGE: {
    id: "PRICE_CHANGE",
    label: "Price change",
    description: "Store-localized price changed. No invented discount.",
    userState: "plus_annual",
    providerAvailable: true,
    connected: true,
    productsAvailable: true,
    lifetimeOwned: false,
    trialState: "converted",
    purchaseOutcome: "already_owned",
    restoreOutcome: "restored",
    subscription: sub("plus", "active", PLUS_ANNUAL, FUTURE),
    priceChange: true,
    billingPeriod: "annual",
    syncDelayMs: 0,
  },
  STORE_UNAVAILABLE: {
    id: "STORE_UNAVAILABLE",
    label: "Store unavailable",
    description: "Billing provider is down.",
    userState: "unknown",
    providerAvailable: false,
    connected: true,
    productsAvailable: false,
    lifetimeOwned: false,
    trialState: "notStarted",
    purchaseOutcome: "unavailable",
    restoreOutcome: "failed",
    syncDelayMs: 0,
  },
  REGION_UNSUPPORTED: {
    id: "REGION_UNSUPPORTED",
    label: "Region unsupported",
    description: "Products are not offered in this storefront.",
    userState: "free",
    providerAvailable: true,
    connected: true,
    productsAvailable: false,
    lifetimeOwned: false,
    trialState: "notStarted",
    purchaseOutcome: "unavailable",
    restoreOutcome: "nothing_found",
    syncDelayMs: 0,
  },
  UNKNOWN_ENTITLEMENT: {
    id: "UNKNOWN_ENTITLEMENT",
    label: "Unknown entitlement",
    description: "Provider has not reported yet. Premium is not assumed.",
    userState: "unknown",
    providerAvailable: false,
    connected: true,
    productsAvailable: true,
    lifetimeOwned: false,
    trialState: "notStarted",
    purchaseOutcome: "success",
    restoreOutcome: "nothing_found",
    syncDelayMs: 0,
  },
  PARTIAL_ENTITLEMENT: {
    id: "PARTIAL_ENTITLEMENT",
    label: "Partial entitlement",
    description: "Only a subset of plus features is enabled.",
    userState: "plus_monthly",
    providerAvailable: true,
    connected: true,
    productsAvailable: true,
    lifetimeOwned: false,
    trialState: "converted",
    purchaseOutcome: "already_owned",
    restoreOutcome: "partial",
    subscription: sub("plus", "active", PLUS_MONTHLY, FUTURE),
    partialFeatures: true,
    billingPeriod: "monthly",
    syncDelayMs: 0,
  },
  SERVER_SYNC_DELAY: {
    id: "SERVER_SYNC_DELAY",
    label: "Server sync delay",
    description: "Store purchase succeeded locally but server confirmation is delayed.",
    userState: "pending",
    providerAvailable: true,
    connected: true,
    productsAvailable: true,
    lifetimeOwned: false,
    trialState: "notStarted",
    purchaseOutcome: "pending",
    restoreOutcome: "partial",
    subscription: sub("plus", "pending", PLUS_ANNUAL),
    billingPeriod: "annual",
    syncDelayMs: 1200,
  },
  PAYMENT_ERROR: {
    id: "PAYMENT_ERROR",
    label: "Payment error",
    description: "Store declined the payment. Premium is not granted.",
    userState: "free",
    providerAvailable: true,
    connected: true,
    productsAvailable: true,
    lifetimeOwned: false,
    trialState: "notStarted",
    purchaseOutcome: "failed",
    restoreOutcome: "nothing_found",
    subscription: sub("free", "active", undefined),
    syncDelayMs: 0,
  },
  RESTORE_USER: {
    id: "RESTORE_USER",
    label: "Existing buyer restore",
    description: "Reinstall path: restore returns lifetime.",
    userState: "lifetime",
    providerAvailable: true,
    connected: true,
    productsAvailable: true,
    lifetimeOwned: true,
    trialState: "ineligible",
    purchaseOutcome: "already_owned",
    restoreOutcome: "restored",
    subscription: sub("lifetime", "active", LIFETIME),
    billingPeriod: "lifetime",
    syncDelayMs: 0,
  },
};

export const MOCK_SCENARIO_LIST = Object.values(MOCK_BILLING_SCENARIOS);

export function getMockScenario(id: MockBillingScenarioId): MockBillingScenario {
  return MOCK_BILLING_SCENARIOS[id];
}
